SBA-28 added seeds functions
Vonterra/sitges-backend pull request #36
Opened 2023-11-23 11:46 UTC by Shazil-55

2023-11-23 12:48 UTC, asim47 requested changes

2023-11-23 12:48 UTC, asim47 commented on src/database/controllers/restaurant.database.ts
> +  async CreateRestaurant(restaurant: Partial<Entities.Restaurant>): Promise<number> {
return type should be string instead of number

2023-11-23 12:48 UTC, asim47 commented on src/database/controllers/restaurant.database.ts
> +      if (err.code === DatabaseErrors.DUPLICATE) {
Why is there a duplicate check? like what's unique in this column? I dont think we need Duplicate check in this function.

2023-11-23 12:48 UTC, asim47 commented on src/database/controllers/restaurantDetail.database.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
All of the functions in this file can be moved to src/database/controllers/restaurant.database.ts we dont need src/database/controllers/restaurantDetail.database.ts

2023-11-23 12:48 UTC, asim47 commented on src/database/controllers/restaurantDetail.database.ts
> +      if (err.code === DatabaseErrors.DUPLICATE) {
No need for duplicate check here as well

2023-11-23 12:48 UTC, asim47 commented on src/seeds/AddRestaurantSeeds.ts
> +const dummyRestaurantDetails = [
dummyRestaurantDetails can just be one object instead of an array of objects

2023-11-23 12:48 UTC, asim47 commented on src/seeds/AddRestaurantSeeds.ts
> +export async function seedRestaurantDeatilsIfRequired() {
No need for this function

2023-11-23 12:48 UTC, asim47 commented on src/seeds/AddRestaurantSeeds.ts
> +      await db.Restaurant.CreateRestaurant(restaurant);
Get id from this function and call the AddRestaurantDetail after this function, that way it will be fully dynamic

2023-11-23 12:48 UTC, asim47 commented on src/seeds/AddRestaurantSeeds.ts
> +const dummyRestaurantDetails = [
And remove restaurantId from static object, you can get it  a dynamic id later from the DB function

2023-11-23 12:56 UTC, Shazil-55 commented
So we don't need to merge the restaurant and restaurant details table?

2023-11-23 13:34 UTC, asim47 requested changes

2023-11-23 13:34 UTC, asim47 commented on src/database/controllers/restaurant.database.ts
> +  async GetRestaurantDetailsCount(): Promise<number> {
why do we need this function?

2023-11-23 13:34 UTC, asim47 commented on tatus
What is this file?

2023-11-23 13:37 UTC, Shazil-55 commented on tatus
i was writing git status maybe a typpo error but there is no file like this in the code

2023-11-24 07:14 UTC, asim47 approved these changes

2023-11-24 07:14 UTC, merged